version: 0.1.{build}
image: Visual Studio 2017
install:
- ps: choco install -i -y --no-progress chicken

environment:
  APPVEYOR_RDP_PASSWORD: Calxy42

build_script:
- ps: .\build-mingw64.ps1

artifacts:
- path: build\*.zip

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
